// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBr36dDrPt5sm1WTd2Iw68lLT0-BROy_c',
    appId: '1:731820579782:web:33bc48573a8726921db0c7',
    messagingSenderId: '731820579782',
    projectId: 'tictactoe-picky',
    authDomain: 'tictactoe-picky.firebaseapp.com',
    storageBucket: 'tictactoe-picky.firebasestorage.app',
    measurementId: 'G-0281VMF3XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD890VLpV1Ce1f6Fjm2VFDMYsGleIAg0qY',
    appId: '1:731820579782:android:414e0dafef42bd001db0c7',
    messagingSenderId: '731820579782',
    projectId: 'tictactoe-picky',
    storageBucket: 'tictactoe-picky.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQhqbnHouwaaOorRkzIMOIS2YThN7egh0',
    appId: '1:731820579782:ios:c97e90b81e0c426c1db0c7',
    messagingSenderId: '731820579782',
    projectId: 'tictactoe-picky',
    storageBucket: 'tictactoe-picky.firebasestorage.app',
    iosBundleId: 'com.example.basico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQhqbnHouwaaOorRkzIMOIS2YThN7egh0',
    appId: '1:731820579782:ios:c97e90b81e0c426c1db0c7',
    messagingSenderId: '731820579782',
    projectId: 'tictactoe-picky',
    storageBucket: 'tictactoe-picky.firebasestorage.app',
    iosBundleId: 'com.example.basico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBr36dDrPt5sm1WTd2Iw68lLT0-BROy_c',
    appId: '1:731820579782:web:4ac82d635e1a6ea61db0c7',
    messagingSenderId: '731820579782',
    projectId: 'tictactoe-picky',
    authDomain: 'tictactoe-picky.firebaseapp.com',
    storageBucket: 'tictactoe-picky.firebasestorage.app',
    measurementId: 'G-70WQT9DLK5',
  );
}
